apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: app
    app: giropops
  name: deployment-brasil-1-15-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
        dc: BR
    spec:
      containers:
      - image: nginx:1.15.0
        imagePullPolicy: Always
        name: app2
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
