apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-11-20T23:51:37Z"
  generation: 1
  labels:
    run: meu-primeiro-deploy
  name: meu-primeiro-deploy
  namespace: default
  resourceVersion: "14381"
  selfLink: /apis/apps/v1/namespaces/default/deployments/meu-primeiro-deploy
  uid: fab31003-dd90-453c-adb4-c73977041cb2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: meu-primeiro-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: meu-primeiro-deploy
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: meu-primeiro-deploy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
