apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app-v1
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
            app: mbr
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbr
    spec:
      containers:
      - image: nginx
        name: mbr
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
