apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: meu-primeiro-deploy
  name: meu-primeiro-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      run: meu-primeiro-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: meu-primeiro-deploy
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: meu-primeiro-deploy
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
