apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: meu-primeiro-deploy
  name: meu-primeiro-deploy
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      run: meu-primeiro-deploy
  template:
    metadata:
      labels:
        run: meu-primeiro-deploy
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: meu-primeiro-deploy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
