apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-12-30T18:34:05Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "152"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: b5246318-5634-47a5-8259-c8d89cd23a93
  spec:
    clusterIP: 10.96.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-12-30T18:57:58Z"
    labels:
      run: meu-primeiro-deploy
    name: meu-primeiro-deploy
    namespace: default
    resourceVersion: "3930"
    selfLink: /api/v1/namespaces/default/services/meu-primeiro-deploy
    uid: 027117fe-bb76-4165-9bf4-5c3090b63d21
  spec:
    clusterIP: 10.96.67.93
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30713
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: meu-primeiro-deploy
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
