apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-12-30T18:54:28Z"
    generation: 1
    labels:
      run: meu-primeiro-deploy
    name: meu-primeiro-deploy
    namespace: default
    resourceVersion: "3414"
    selfLink: /apis/apps/v1/namespaces/default/deployments/meu-primeiro-deploy
    uid: 80675b1a-77ed-4a1b-a1b6-9cc6559740e9
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: meu-primeiro-deploy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: meu-primeiro-deploy
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: meu-primeiro-deploy
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-12-30T18:54:34Z"
      lastUpdateTime: "2019-12-30T18:54:34Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-12-30T18:54:28Z"
      lastUpdateTime: "2019-12-30T18:54:34Z"
      message: ReplicaSet "meu-primeiro-deploy-75b4774576" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
