apiVersion: v1
kind: Service
metadata:
  labels:
    run: meu-primeiro-deploy-nodeport
  name: meu-primeiro-deploy-nodeport
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: meu-primeiro-deploy-nodeport
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
